name: integration-test

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      namespace:
        required: false
        default: fulfillment
        type: string
      branch:
        required: true
        type: string
      test_runner_service_name:
        required: false
        default: integration-test-runner
        type: string
      test_runner_endpoint:
        required: false
        default: sanity
        type: string
    secrets:
      git_token:
        required: true
      gcloud_token:
        required: true
      gcr_token:
        required: false
      slack_token:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: gcr login
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.gcr_token }}

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: clone repository
      uses: actions/checkout@v2
      with:
        path: ${{ inputs.service_name }}
        repository: get-fabric/${{ inputs.service_name }}
        ref: ${{ inputs.branch }}
        token: ${{ secrets.git_token }}

    - name: build image
      uses: docker/build-push-action@v2
      with:
        context: ./${{ inputs.service_name }}
        build-args: |
          NPM_TOKEN=${{ secrets.git_token }}
        tags: gcr.io/fabric-registry/cloud-services/${{ inputs.service_name }}:${{ github.event.pull_request.head.sha || github.sha }}
        push: true
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, scope=${{ github.workflow }}

  sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: setup -> started
        id: start_time
        run: echo "::set-output name=time::$(date +%s)"

      - name: "setup -> install helm"
        uses: azure/setup-helm@v1
        with:
          version: latest

      - name: setup -> gcloud login
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcloud_token }}'

      - name: setup -> install gcloud cli
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: setup -> clone integration-environment repository
        uses: actions/checkout@v2
        with:
          path: integration-environment
          repository: get-fabric/integration-environment
          token: ${{ secrets.git_token }}

      - name: setup -> clone fulfillment-integration-tests repository
        uses: actions/checkout@v2
        with:
          path: fulfillment-integration-tests
          repository: get-fabric/fulfillment-integration-tests
          token: ${{ secrets.git_token }}

      - name: setup -> clone tested service repository
        uses: actions/checkout@v2
        with:
          repository: get-fabric/${{ inputs.service_name }}
          path: ${{ inputs.service_name }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.git_token }}

      - name: create vcluster
        id: create_vcluster
        run: |
          gcloud container clusters get-credentials integration --region us-east4 --project fabric-global-test
          curl -s -L "https://github.com/loft-sh/vcluster/releases/latest" | sed -nE 's!.*"([^"]*vcluster-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o vcluster && chmod +x vcluster;
          sudo mv vcluster /usr/local/bin;
          cluster_name=integration-tests-$(date +%s)
          echo "::set-output name=cluster_name::$cluster_name"
          vcluster create $cluster_name --namespace vcluster
          bash ./fulfillment-integration-tests/wait_for_pod_ready.sh $cluster_name-0 vcluster ./kubeconfig.yaml
          sleep 90 # waiting for vcluster to finish initalization
          vcluster connect $cluster_name -n vcluster &
          sleep 10

      - name: wait for image build
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.git_token }}
          checkName: integration-test / build-image
          intervalSeconds: 1
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 120

      - name: deploy services
        run: |
          helm template --dependency-update -f ./${{ inputs.service_name }}/deployment/values.yaml -f ./${{ inputs.service_name }}/deployment/values.integration.yaml --name-template=${{ inputs.service_name }} --set fabric-chart.image.tag="${{ github.event.pull_request.head.sha || github.sha }}" ./${{ inputs.service_name }}/deployment > ./integration-environment/deployments/${{ inputs.namespace }}/${{ inputs.service_name }}.yaml
          kubectl --kubeconfig ./kubeconfig.yaml create namespace fulfillment || true
          kubectl --kubeconfig ./kubeconfig.yaml create namespace job-management || true
          kubectl --kubeconfig ./kubeconfig.yaml apply -f ./integration-environment/deployments/default --validate=false || true
          kubectl --kubeconfig ./kubeconfig.yaml apply -f ./integration-environment/deployments/fulfillment -n fulfillment --validate=false || true
          kubectl --kubeconfig ./kubeconfig.yaml apply -f ./integration-environment/deployments/job-management -n job-management --validate=false || true
          bash ./fulfillment-integration-tests/wait_for_pods.sh default "Running|ContainerCreating|Pending" 1 ./kubeconfig.yaml
          bash ./fulfillment-integration-tests/wait_for_pods.sh fulfillment "Running|ContainerCreating|Pending" 1 ./kubeconfig.yaml
          bash ./fulfillment-integration-tests/wait_for_pods.sh job-management "Running|ContainerCreating|Pending" 1 ./kubeconfig.yaml
          kubectl --kubeconfig ./kubeconfig.yaml get pods -A

      - name: run test
        run: bash ./fulfillment-integration-tests/test.sh ${{ inputs.test_runner_service_name }} ${{ inputs.test_runner_endpoint }} ./kubeconfig.yaml

      - name: cleanup
        if: always()
        run: |
          kubectl --kubeconfig ./kubeconfig.yaml get pods -A
          vcluster delete ${{steps.create_vcluster.outputs.cluster_name}} --namespace vcluster

      - name: teardown -> calculate exeuction time
        id: exexution_time
        if: always()
        run: |
          startTime=${{ steps.start_time.outputs.time }}
          currentTime=$(date +%s)
          executionTimeSeconds=$((currentTime-startTime))
          ((sec=executionTimeSeconds%60, executionTimeSeconds/=60, min=executionTimeSeconds%60))
          executionTime=$(printf "%02d:%02d" $min $sec)
          echo "::set-output name=time::$executionTime"

      - name: teardown -> report cancelled
        if: cancelled()
        uses: actions-ecosystem/action-slack-notifier@v1
        with:
          slack_token: ${{ secrets.slack_token }}
          message: |
            ${{ inputs.test_runner_endpoint }} integration test was cancelled
          color: yellow
          channel: fulfillment-integration-tests-monitoring
          verbose: true

      - name: teardown -> report failure
        if: failure()
        continue-on-error: true
        uses: actions-ecosystem/action-slack-notifier@v1
        with:
          slack_token: ${{ secrets.slack_token }}
          message: |
            ${{ inputs.test_runner_endpoint }} integration test failed after ${{ steps.exexution_time.outputs.time }} minutes
          color: red
          channel: fulfillment-integration-tests-monitoring
          verbose: true

      - name: teardown -> report success
        if: success()
        continue-on-error: true
        uses: actions-ecosystem/action-slack-notifier@v1
        with:
          slack_token: ${{ secrets.slack_token }}
          message: |
            ${{ inputs.test_runner_endpoint }} integration test succeeded after ${{ steps.exexution_time.outputs.time }} minutes
          color: green
          channel: fulfillment-integration-tests-monitoring
          verbose: true
